name: 01 Hello Workflow
#hello
on:
  pull_request:
    types: 
      - closed
  push:
    paths:
      - ".github/workflows/01-hello.yml"
  workflow_dispatch:

jobs:
  say-hello:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions - Merge Confirmed"